-- PermutApp - ServicioLocalizacion en Supabase/PostgreSQL
-- Ejecutar en el SQL Editor del proyecto Supabase de localizacion.
-- Fuente recomendada para completar/actualizar estaciones: Datos Abiertos Chile, recurso
-- "Lugares de carga de tarjeta bip!_ Estaciones de Metro" de Metro S.A.

create table if not exists pais (
  pais_id integer generated by default as identity primary key,
  pais_nombre varchar(120) not null
);

create table if not exists region (
  regi_id integer generated by default as identity primary key,
  regi_nombre varchar(120) not null,
  pais_id integer not null references pais(pais_id) on delete cascade
);

create table if not exists ciudad (
  ciudad_id integer generated by default as identity primary key,
  ciudad_nombre varchar(120) not null,
  regi_id integer not null references region(regi_id) on delete cascade
);

create table if not exists comuna (
  comu_id integer generated by default as identity primary key,
  comu_nombre varchar(120) not null,
  ciu_id integer not null references ciudad(ciudad_id) on delete cascade
);

create table if not exists direccion (
  add_id integer generated by default as identity primary key,
  add_calle varchar(180),
  add_numero integer,
  add_letra varchar(20),
  comu_id integer references comuna(comu_id)
);

create table if not exists punto_encuentro (
  sug_id_punto_encuentro integer generated by default as identity primary key,
  latitud double precision,
  longitud double precision,
  referencias text,
  comu_id integer references comuna(comu_id)
);

create table if not exists estacion_metro (
  id integer generated by default as identity primary key,
  nombre varchar(120) not null,
  linea varchar(20) not null,
  orden integer,
  es_combinacion boolean default false,
  latitud double precision,
  longitud double precision,
  direccion varchar(220),
  comuna varchar(120)
);

create unique index if not exists pais_nombre_uidx on pais (lower(pais_nombre));
create unique index if not exists region_nombre_pais_uidx on region (lower(regi_nombre), pais_id);
create unique index if not exists ciudad_nombre_region_uidx on ciudad (lower(ciudad_nombre), regi_id);
create unique index if not exists comuna_nombre_ciudad_uidx on comuna (lower(comu_nombre), ciu_id);
create unique index if not exists estacion_metro_nombre_linea_uidx on estacion_metro (lower(nombre), lower(linea));

alter table estacion_metro
  add column if not exists latitud double precision,
  add column if not exists longitud double precision,
  add column if not exists direccion varchar(220),
  add column if not exists comuna varchar(120);

insert into pais (pais_nombre)
values ('Chile')
on conflict do nothing;

insert into region (regi_nombre, pais_id)
select 'Region Metropolitana', pais_id from pais where pais_nombre = 'Chile'
on conflict do nothing;

insert into ciudad (ciudad_nombre, regi_id)
select 'Santiago', regi_id from region where regi_nombre = 'Region Metropolitana'
on conflict do nothing;

-- Seed ampliado para estaciones de Metro con coordenadas reales desde capa publica ArcGIS.
-- Nota: L7, L8 y L9 quedan como botones en la app, pero sin estaciones cargadas hasta tener coordenadas oficiales operativas.
create temporary table if not exists tmp_estacion_metro_seed (
  nombre varchar(120) not null,
  linea varchar(20) not null,
  orden integer,
  es_combinacion boolean default false,
  latitud double precision,
  longitud double precision,
  direccion varchar(220),
  comuna varchar(120)
) on commit drop;

truncate table tmp_estacion_metro_seed;

insert into tmp_estacion_metro_seed (nombre, linea, orden, es_combinacion, latitud, longitud, direccion, comuna) values
('San Pablo', 'L1', 1, true, -33.4441895493096, -70.7232885295238, null, null),
('Neptuno', 'L1', 2, false, -33.4519325188292, -70.7225384535852, null, null),
('Pajaritos', 'L1', 3, false, -33.4578262836353, -70.7134030021858, null, null),
('Las Rejas', 'L1', 4, false, -33.4572381556193, -70.7064745878902, null, null),
('Ecuador', 'L1', 5, false, -33.4561893219750, -70.7010540388778, null, null),
('San Alberto Hurtado', 'L1', 6, false, -33.4542558932224, -70.6922912963922, null, null),
('Universidad de Santiago', 'L1', 7, false, -33.4526042063050, -70.6862764108913, null, null),
('Estacion Central', 'L1', 8, false, -33.4508943874567, -70.6799652274033, null, null),
('Union Latinoamericana', 'L1', 9, false, -33.4496517732411, -70.6743659116455, null, null),
('Republica', 'L1', 10, false, -33.4468959493874, -70.6642448520769, null, null),
('Los Heroes', 'L1', 11, true, -33.4462814285225, -70.6604447474867, null, null),
('La Moneda', 'L1', 12, false, -33.4452451580749, -70.6557810269516, null, null),
('Universidad de Chile', 'L1', 13, true, -33.4442955966118, -70.6517220563516, null, null),
('Santa Lucia', 'L1', 14, false, -33.4429851950970, -70.6464588815257, null, null),
('Universidad Catolica', 'L1', 15, false, -33.4407987487585, -70.6410296403953, null, null),
('Baquedano', 'L1', 16, true, -33.4373094107511, -70.6332882714140, null, null),
('Salvador', 'L1', 17, false, -33.4341440809603, -70.6261997001865, null, null),
('Manuel Montt', 'L1', 18, false, -33.4289742002976, -70.6193876026189, null, null),
('Pedro de Valdivia', 'L1', 19, false, -33.4256626931254, -70.6138003736448, null, null),
('Los Leones', 'L1', 20, true, -33.4226379248110, -70.6089251611236, null, null),
('Tobalaba', 'L1', 21, true, -33.4184862299736, -70.6016641801424, null, null),
('El Golf', 'L1', 22, false, -33.4165776760031, -70.5955702059519, null, null),
('Alcantara', 'L1', 23, false, -33.4153595288739, -70.5896808968626, null, null),
('Escuela Militar', 'L1', 24, false, -33.4141838217081, -70.5843110380417, null, null),
('Manquehue', 'L1', 25, false, -33.4091408674000, -70.5684291380973, null, null),
('Hernando de Magallanes', 'L1', 26, false, -33.4077535826152, -70.5568743241157, null, null),
('Los Dominicos', 'L1', 27, false, -33.4078940260839, -70.5448498352736, null, null),
('Vespucio Norte', 'L2', 1, false, -33.3801967585275, -70.6465139262460, null, null),
('Zapadores', 'L2', 2, false, -33.3909810721993, -70.6424092101355, null, null),
('Dorsal', 'L2', 3, false, -33.3970181272519, -70.6426776602094, null, null),
('Einstein', 'L2', 4, false, -33.4066024836564, -70.6430269260008, null, null),
('Cementerios', 'L2', 5, false, -33.4140381163510, -70.6433733542498, null, null),
('Cerro Blanco', 'L2', 6, false, -33.4221817256352, -70.6449483392731, null, null),
('Patronato', 'L2', 7, false, -33.4296626786608, -70.6470439411899, null, null),
('Puente Cal y Canto', 'L2', 8, true, -33.4330738594289, -70.6532327437442, null, null),
('Santa Ana', 'L2', 9, true, -33.4383757138624, -70.6596648150306, null, null),
('Los Heroes', 'L2', 10, true, -33.4462814285225, -70.6604447474867, null, null),
('Toesca', 'L2', 11, false, -33.4536553242918, -70.6583512922798, null, null),
('Parque O''Higgins', 'L2', 12, false, -33.4604352687099, -70.6564268340579, null, null),
('Rondizzoni', 'L2', 13, false, -33.4699752072452, -70.6559421829235, null, null),
('Franklin', 'L2', 14, true, -33.4764780300030, -70.6491927538438, null, null),
('El Llano', 'L2', 15, false, -33.4819690946593, -70.6497241243260, null, null),
('San Miguel', 'L2', 16, false, -33.4889185487310, -70.6507949817575, null, null),
('Lo Vial', 'L2', 17, false, -33.4964982523913, -70.6528271240302, null, null),
('Departamental', 'L2', 18, false, -33.5034335286243, -70.6549557868557, null, null),
('Ciudad del Nino', 'L2', 19, false, -33.5116936917353, -70.6570780791716, null, null),
('Lo Ovalle', 'L2', 20, false, -33.5179859175857, -70.6590850657059, null, null),
('El Parron', 'L2', 21, false, -33.5266447641575, -70.6612634875271, null, null),
('La Cisterna', 'L2', 22, true, -33.5375661747140, -70.6641952959095, null, null),
('Cardenal Caro', 'L3', 5, false, -33.3736108021268, -70.6864304359522, null, null),
('Vivaceta', 'L3', 6, false, -33.3859269188792, -70.6793259801501, null, null),
('Conchali', 'L3', 7, false, -33.3979239108515, -70.6697728726656, null, null),
('Plaza Chacabuco', 'L3', 8, false, -33.4065172626861, -70.6611201626330, null, null),
('Hospitales', 'L3', 9, false, -33.4177736751268, -70.6562801299892, null, null),
('Puente Cal y Canto', 'L3', 10, true, -33.4330738594289, -70.6532327437442, null, null),
('Plaza de Armas', 'L3', 11, true, -33.4375859704784, -70.6507579492033, null, null),
('Universidad de Chile', 'L3', 12, true, -33.4442955966118, -70.6517220563516, null, null),
('Parque Almagro', 'L3', 13, false, -33.4518486644689, -70.6505696483649, null, null),
('Matta', 'L3', 14, false, -33.4583566344736, -70.6433445568871, null, null),
('Irarrazaval', 'L3', 15, true, -33.4524508107646, -70.6290406945740, null, null),
('Monseñor Eyzaguirre', 'L3', 16, false, -33.4532453094204, -70.6136731124783, null, null),
('Nunoa', 'L3', 17, true, -33.4541694552221, -70.6050080334914, null, null),
('Chile España', 'L3', 18, false, -33.4547874399297, -70.5983597831629, null, null),
('Huechuraba', 'L3', 22, false, -33.3665086683468, -70.6894316722530, null, null),
('Larrain', 'L3', 23, false, -33.4521869147703, -70.5589577225685, null, null),
('Diagonal Oriente', 'L3', 24, false, -33.4547498770132, -70.5801876056948, null, null),
('Tobalaba', 'L4', 1, true, -33.4184862299736, -70.6016641801424, null, null),
('Cristobal Colon', 'L4', 2, false, -33.4265295710860, -70.5912090291461, null, null),
('Francisco Bilbao', 'L4', 3, false, -33.4317175526537, -70.5848286252660, null, null),
('Principe de Gales', 'L4', 4, false, -33.4381032003105, -70.5735397454335, null, null),
('Simon Bolivar', 'L4', 5, false, -33.4480246786515, -70.5717147046450, null, null),
('Los Orientales', 'L4', 7, false, -33.4590477298684, -70.5722034849363, null, null),
('Grecia', 'L4', 8, false, -33.4689061864731, -70.5763196654363, null, null),
('Los Presidentes', 'L4', 9, false, -33.4814045734737, -70.5792275378416, null, null),
('Quilin', 'L4', 10, false, -33.4877700468363, -70.5801337069808, null, null),
('Las Torres', 'L4', 11, false, -33.5002880403036, -70.5871172199117, null, null),
('Macul', 'L4', 12, false, -33.5078809246600, -70.5898862908332, null, null),
('Vicuna Mackenna', 'L4', 13, true, -33.5218435457784, -70.5975137809302, null, null),
('Vicente Valdes', 'L4', 14, true, -33.5264955551145, -70.5965021479863, null, null),
('Rojas Magallanes', 'L4', 15, false, -33.5355626060666, -70.5928370493258, null, null),
('Trinidad', 'L4', 16, false, -33.5471219522920, -70.5876809438422, null, null),
('Los Quillayes', 'L4', 17, false, -33.5645917878309, -70.5844442766570, null, null),
('Elisa Correa', 'L4', 18, false, -33.5689523531882, -70.5837043561629, null, null),
('Hospital Sotero del Rio', 'L4', 19, false, -33.5760965125451, -70.5819455079579, null, null),
('Protectora de la Infancia', 'L4', 20, false, -33.5858551386495, -70.5802625925502, null, null),
('Las Mercedes', 'L4', 21, false, -33.5941574600372, -70.5788154697052, null, null),
('Plaza Puente Alto', 'L4', 22, false, -33.6093702375755, -70.5758486831562, null, null),
('Plaza Egaña', 'L4', 65, false, -33.4534819267586, -70.5708091454529, null, null),
('La Cisterna', 'L4A', 1, true, -33.5375661747140, -70.6641952959095, null, null),
('San Ramon', 'L4A', 2, false, -33.5412046621782, -70.6433162307882, null, null),
('Santa Rosa', 'L4A', 3, false, -33.5425154965582, -70.6341413946416, null, null),
('La Granja', 'L4A', 4, false, -33.5376493232418, -70.6099648126666, null, null),
('Santa Julia', 'L4A', 5, false, -33.5311793436307, -70.6054423508582, null, null),
('Vicuna Mackenna', 'L4A', 6, true, -33.5218435457784, -70.5975137809302, null, null),
('Plaza de Maipu', 'L5', 1, false, -33.5104905971795, -70.7571658502422, null, null),
('Santiago Bueras', 'L5', 2, false, -33.4963897197621, -70.7573803172831, null, null),
('Del Sol', 'L5', 3, false, -33.4889479412597, -70.7520933538652, null, null),
('Monte Tabor', 'L5', 4, false, -33.4821387353957, -70.7451309299808, null, null),
('Las Parcelas', 'L5', 5, false, -33.4753144125047, -70.7397283084099, null, null),
('Laguna Sur', 'L5', 6, false, -33.4628175223006, -70.7378135578630, null, null),
('Barrancas', 'L5', 7, false, -33.4524414479452, -70.7391762010878, null, null),
('Ricardo Cumming', 'L5', 7, false, -33.4387791785264, -70.6644951422769, null, null),
('Pudahuel', 'L5', 8, false, -33.4447327949532, -70.7406491012186, null, null),
('San Pablo', 'L5', 9, true, -33.4441895493096, -70.7232885295238, null, null),
('Lo Prado', 'L5', 10, false, -33.4431112566683, -70.7157402734013, null, null),
('Blanqueado', 'L5', 11, false, -33.4414418276839, -70.7071813991128, null, null),
('Gruta de Lourdes', 'L5', 12, false, -33.4380879348105, -70.6911874889366, null, null),
('Quinta Normal', 'L5', 13, false, -33.4403440798742, -70.6800734685287, null, null),
('Santa Ana', 'L5', 15, true, -33.4383757138624, -70.6596648150306, null, null),
('Plaza de Armas', 'L5', 16, true, -33.4375859704784, -70.6507579492033, null, null),
('Bellas Artes', 'L5', 17, false, -33.4362986411631, -70.6432741403911, null, null),
('Baquedano', 'L5', 18, true, -33.4373094107511, -70.6332882714140, null, null),
('Parque Bustamante', 'L5', 19, false, -33.4413791890142, -70.6321978852550, null, null),
('Santa Isabel', 'L5', 20, false, -33.4471521955106, -70.6302639203060, null, null),
('Irarrazaval', 'L5', 21, true, -33.4524508107646, -70.6290406945740, null, null),
('Nuble', 'L5', 22, true, -33.4671703574410, -70.6249128167889, null, null),
('Rodrigo de Araya', 'L5', 23, false, -33.4766893676758, -70.6224711577377, null, null),
('Carlos Valdovinos', 'L5', 24, false, -33.4863019940656, -70.6191657711169, null, null),
('San Joaquin', 'L5', 26, false, -33.4961550686448, -70.6164085931574, null, null),
('Pedrero', 'L5', 27, false, -33.5079730072836, -70.6131830231273, null, null),
('Mirador', 'L5', 28, false, -33.5131093364346, -70.6061307671229, null, null),
('Bellavista de La Florida', 'L5', 29, false, -33.5206805503697, -70.5987179941017, null, null),
('Vicente Valdes', 'L5', 30, true, -33.5264955551145, -70.5965021479863, null, null),
('Cerrillos', 'L6', 1, false, -33.4833088251866, -70.6952924997270, null, null),
('Lo Valledor', 'L6', 2, false, -33.4762926087901, -70.6802960685304, null, null),
('Franklin', 'L6', 4, true, -33.4764780300030, -70.6491927538438, null, null),
('Bio Bio', 'L6', 5, false, -33.4763562279478, -70.6421861116224, null, null),
('Nuble', 'L6', 6, true, -33.4671703574410, -70.6249128167889, null, null),
('Estadio Nacional', 'L6', 7, false, -33.4624574528369, -70.6063873907723, null, null),
('Nunoa', 'L6', 8, true, -33.4541694552221, -70.6050080334914, null, null),
('Ines de Suarez', 'L6', 9, false, -33.4385617334740, -70.6075603009336, null, null),
('Los Leones', 'L6', 10, true, -33.4226379248110, -70.6089251611236, null, null),
('Club Hipico', 'L6', 105, false, -33.4763962382219, -70.6651150536021, null, null);


update estacion_metro em
set
  orden = seed.orden,
  es_combinacion = seed.es_combinacion,
  latitud = seed.latitud,
  longitud = seed.longitud,
  direccion = coalesce(seed.direccion, em.direccion),
  comuna = coalesce(seed.comuna, em.comuna)
from tmp_estacion_metro_seed seed
where lower(em.nombre) = lower(seed.nombre)
  and lower(em.linea) = lower(seed.linea);

insert into estacion_metro (nombre, linea, orden, es_combinacion, latitud, longitud, direccion, comuna)
select seed.nombre, seed.linea, seed.orden, seed.es_combinacion, seed.latitud, seed.longitud, seed.direccion, seed.comuna
from tmp_estacion_metro_seed seed
where not exists (
  select 1
  from estacion_metro em
  where lower(em.nombre) = lower(seed.nombre)
    and lower(em.linea) = lower(seed.linea)
);
