package com.example.PermutApp.model.entities;

public enum TipoNotificacion {
   MENSAJE_NUEVO,
   PROPUESTA_PERMUTA,
   OFERTA_COMPARTIDA,
   FINALIZACION_SOLICITADA,
   PERMUTA_FINALIZADA,
   VALORACION_RECIBIDA,
   IDENTIDAD_APROBADA,
   IDENTIDAD_RECHAZADA,
   IDENTIDAD_REVISION
}
